language: node_js
node_js:
	- "5.2.8"
script: npm test
before_install:
	- git clone git://github.com/n1k0/casperjs.git ~/casperjs
	- cd ~/casperjs
	- git checkout tags/1.0.2
	- export PATH=$PATH:`pwd`/bin
	- cd -
before_script:
  - phantomjs --version
  - casperjs --version	